### ISSUE TITLE
No method error using Rails.configuration.launched

### ISSUE THREAD

**Issue by rkrdo** [RailsApps/rails-prelaunch-signup#11]
I get [this](http://screencloud.net/v/CpSS) when adding `Rails.configuration.launched` to the **app/views/devise/shared/_links.html.haml**, did I miss anything?

**Comment by DanielKehoe** [comment]
Are you following the tutorial or just using the example app from the repo? If you follow the tutorial and get errors, download the example app and use a file compare tool to identify differences that may be causing errors in your own code. Check that you have the file config/initializers/prelaunch-signup.rb.

**Comment by rkrdo** [comment]
I'm following the tutorial, my application has a different name. Does the file still need to be named prelaunch-signup.rb?

**Comment by DanielKehoe** [comment]
Yes, the file must be named prelaunch-signup.rb.

**Comment by rkrdo** [comment]
Ok, now it works, I thought you had to name that file like your application, thanks
