### ISSUE TITLE
errors with rvm installing starter app

### ISSUE THREAD

**Issue by ghost** [RailsApps/rails-prelaunch-signup#13]
Trying to install the starter app gives me this error when it gets to the line extras  Banning spiders by modifying 'public/robots.txt'

https://raw.github.com/RailsApps/rails3-application-templates/master/rails3-bootstrap-devise-cancan-template.rb:1084:in `rescue in apply': RVM ruby lib is currently unavailable. (RuntimeError)
    from https://raw.github.com/RailsApps/rails3-application-templates/master/rails3-bootstrap-devise-cancan-template.rb:1079:in`apply'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/thor-0.16.0/lib/thor/actions.rb:221:in `instance_eval'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/thor-0.16.0/lib/thor/actions.rb:221:in`apply'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/railties-3.2.8/lib/rails/generators/app_base.rb:109:in `apply_rails_template'
    from (eval):1:in`apply_rails_template'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/thor-0.16.0/lib/thor/invocation.rb:120:in`invoke_task'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `block in invoke_all'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/thor-0.16.0/lib/thor/invocation.rb:126:in`each'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `map'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/thor-0.16.0/lib/thor/invocation.rb:126:in`invoke_all'
    from /Users/ml/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/thor-0.16.0/lib/thor/group.rb:238:in `dispatch'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/thor-0.16.0/lib/thor/base.rb:425:in`start'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/railties-3.2.8/lib/rails/commands/application.rb:38:in `<top (required)>'
    from /Users/m/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from /Users/m/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/railties-3.2.8/lib/rails/cli.rb:15:in`<top (required)>'
    from /Users/m/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/m/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/gems/railties-3.2.8/bin/rails:7:in `<top (required)>'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/bin/rails:19:in`load'
    from /Users/m/.rvm/gems/ruby-1.9.3-rc1@ruby193/bin/rails:19:in `<main>'

**Comment by DanielKehoe** [comment]
I need some clarification. Are you following the tutorial for the rails-prelaunch-signup app? At the step in the instructions just below "Create the Rails Application" where you use an app template to create an application with the following command:

$ rails new rails-prelaunch-signup -m https://raw.github.com/RailsApps/rails3-application-templates/master/rails3-bootstrap-devise-cancan-template.rb -T

??

**Comment by ghost** [comment]
Yes, that's right. I'm trying to install the starter app in the section
"Create the Rails Application"

**Comment by DanielKehoe** [comment]
Could you try this instead and choose "rails3-bootstrap-devise-cancan" at the prompt:
$ rails new myapp -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb

**Comment by DanielKehoe** [comment]
Closing this issue due to lack of response.

**Comment by ajmalafif** [comment]
Hello there, I am having the same type of issues over here too.

My error happens right after I answered creating Github repo (y/n): yes or no gave the same error.

https://gist.github.com/3527327

I started with the rails3-bootstrap-devise-cancan and it worked: https://github.com/ajmalafif/pasar-railsapp

Will try things out and share any findings or positive result here.

**Comment by DanielKehoe** [comment]
It's a problem with your rvm installation. See if you can manually create a new gemset using rvm. You might try reinstalling rvm. Make sure you have the newest version of rvm. And review the article [Installing Rails](http://railsapps.github.com/installing-rails.html). Let me know how it goes.

**Comment by ajmalafif** [comment]
_See if you can manually create a new gemset using rvm._
I can manually create a new gemset. See below.

_You might try reinstalling rvm. Make sure you have the newest version of rvm._ 
rvm 1.15.8 (latest) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]

_And review the article Installing Rails._

Upgraded rubygems-bundler and bundle. Upgraded Rails to v3.2.8.

```
[~]$ rails -v
Rails 3.2.8

[market (master)]$ rvm list

rvm rubies

   ruby-1.9.2-p290 [ x86_64 ]
   ruby-1.9.2-p318 [ x86_64 ]
 * ruby-1.9.3-p125 [ x86_64 ]
=> ruby-1.9.3-p194 [ x86_64 ]

   #  => - current
   #  =* - current && default
   #  * - default

 [market (master)]$ rvm gemset list

gemsets for ruby-1.9.3-p194 (found in /Users/ajmalafif/.rvm/gems/ruby-1.9.3-p194)
   global
=> rails328
```

Same exact error. Anything else (Xcode? osx 10.7.4?). I'm still googling and looking around for solution. WIll share any positive result and findings. So far I can't pass through this.

**Comment by DanielKehoe** [comment]
Before it gets frustrating, you could just skip the "project-specific rvm gemset and .rvmrc" option (say "no"). That's the most expedient resolution. You can manually create a gemset. You don't need to use the tool to  do so.

If you want to take the time to fully resolve the issue, try reinstalling rvm. I've seen rvm issues go away after a reinstall.

Let me know how it goes.

**Comment by ajmalafif** [comment]
Well I sort of trying to get used of hitting those walls, so even if I do,
it won't be channeled here or on someone/something else :)

Thanks for the help and guidance. Will do that and get back soon.

**Comment by ajmalafif** [comment]
Oh and btw, I can't answer "no" because it breaks after answering create
repo in github (regardless of answering yes or no).

But good news, I restart iTerm before attempting rvm reinstall and gave it
another try. Voila! It's running pass thru rvmrc part.

Thanks again for the awesome guide and app!

**Comment by DanielKehoe** [comment]
Excellent. I'll advise people to restart the terminal if they encounter this issue.
