### ISSUE TITLE
To fix two broken rspec specs

### ISSUE THREAD

**Issue by jasnow** [RailsApps/rails-prelaunch-signup#17]
1. Add **"validates_confirmation_of :password"** line (15) to add/models/user.rb file.
2. Changed "false" to **'!(password != "")'** inside "if !persisted?" (line 19) inside app/models/user.rb file.

**Comment by padi** [comment]
+1. I will make a pull request if you haven't yet.

**Comment by jasnow** [comment]
thanks

**Comment by DanielKehoe** [comment]
@jasnow thanks for bringing this up.

@padi thanks for the pull request.

I've also updated the spec_helper.rb file to configure DatabaseCleaner properly.
