### ISSUE TITLE
App crashes on remove_user_from_mailchimp if user doesn't exist on mailing list

### ISSUE THREAD

**Issue by mattmenefee** [RailsApps/rails-prelaunch-signup#22]
If the user has already unsubscribed from the mailchimp mailing list so that they are no longer a member of the list, and then goes to delete his account from the rails prelaunch signup application, the app crashes because it isn't able to successfully unsubscribe the user.  What would be the best way to prevent this exception?  Perhaps first check to see if the user is a member of the mailing before attempting to unsubscribe the user?

**Comment by DanielKehoe** [comment]
This issue is resolved in the most recent release.
