### ISSUE TITLE
Cannot log in as admin user (user@example.com)

### ISSUE THREAD

**Issue by jmcaffee** [RailsApps/rails-prelaunch-signup#25]
I'm following the rails pre-launch tutorial and I'm to the Feature: View Progress section.
My cucumber tests are failing AND I'm unable to login to the app as the admin user. When I login, the next page states 'Your account is not active."

I've pulled down rails-prelaunch-signup and compared the code with what I currently have but nothing jumps out as being different.

user@example.com does have the admin role but the app still redirects to the devise/registrations#new screen.

**Comment by jmcaffee** [comment]
I've completed the View Progress section without success. The cucumber test fails as well (logging in as admin) with the following:

```
Scenario: Administrator views list of users          # features/admin/view_progress.feature:6

Given I request an invitation with valid user data # features/step_definitions/visitor_steps.rb:51
And I am logged in as an administrator             # features/step_definitions/admin_steps.rb:1
When I visit the users page                        # features/step_definitions/admin_steps.rb:10
Then I should see a list of users                  # features/step_definitions/admin_steps.rb:15
  expected there to be content "example@example.com" in "DigiSpector\n    \n          DigiSpector\n\n
Login  \n    \n    \n    Sign up\n    \n\n      \n      \n        \n           \n            \n                  \n      
A-\n      You need to sign in or sign up before continuing.\n    \n\n              Sign in\n\n  Email\n  Password\n
Remember me\n    Sign upForgot your password?Didn't receive confirmation instructions?\n  \n  \n  \n  \n
(RSpec::Expectations::ExpectationNotMetError)
  ./features/step_definitions/admin_steps.rb:16:in `/^I should see a list of users$/'
  features/admin/view_progress.feature:10:in `Then I should see a list of users'
```

**Comment by jmcaffee** [comment]
I got my view_progress tests to pass by setting the confirmation attributes in my step definitions.
`features/step_definitions/admin_steps.rb`:

``` ruby
Given /^I am logged in as an administrator$/ do
     @admin = FactoryGirl.create(:user, email: "admin@example.com")
     @admin.add_role :admin
+    @admin.update_attribute(:confirmation_token, nil)
+    @admin.update_attribute(:confirmed_at, Time.now)
     @visitor ||= { :email => "admin@example.com",
                    :password => "please", :password_confirmation => "please" }
     sign_in
   end
```

and `features/step_definitions/user_steps.rb`:

``` ruby
def create_user
  create_visitor
  delete_user
  @user = FactoryGirl.create(:user, email: @visitor[:email])
+  @user.update_attribute(:confirmation_token, nil)
+  @user.update_attribute(:confirmed_at, Time.now)
end
```

Fixed my manual login problem (using user@example.com) by adding the following to `db/seeds.rb`:

``` ruby
    user.add_role :admin
+    user.update_attribute(:confirmation_token, nil)
+    user.update_attribute(:confirmed_at, Time.now)
    user2.add_role :VIP
```

then running `rake db:reset` to rebuild the DB.

All is well!

**Comment by DanielKehoe** [comment]
I'm glad you resolved the issues.

I took a look to see if the tutorial or the example application might have errors but I couldn't find any.

The tutorial shows the seeds.rb file as:

```
puts 'SETTING UP DEFAULT USER LOGIN'
user = User.create! :name => 'First User', :email => 'user@example.com', :password => 'please', :password_confirmation => 'please'
user.confirm!
puts 'New user created: ' << user.name
user2 = User.create! :name => 'Second User', :email => 'user2@example.com', :password => 'please', :password_confirmation => 'please'
user2.confirm!
puts 'New user created: ' << user2.name
user.add_role :admin
```

The line `user.confirm!` should have the same effect as the `user.update_attribute` you added.

**Comment by davidmolina** [comment]
Daniel,
Thanks for pulling this together-- tutorial was very easy to use, and its visible in localhost:3000. Problem is the request invitation doesn't work. After you put in an email, any email, and click "request invitation" nothing happens. It's as if the link doesn't work. Used to, but its not working anymore. Ideas? Thanks, David

**Comment by DanielKehoe** [comment]
I suggest to clone the example app from GitHub and try it. Does the example work? If it does, compare the code with a fil diff tool and see if there are differences. Let me know what you find out.

**Comment by davidmolina** [comment]
Daniel, thanks. Let me try that and see if it works. I'll let you know.

**Comment by davidmolina** [comment]
Daniel, 
I worked through in reverse order. The following I replaced w/ the original code:

```
RailsPrelaunchSignup::Application.routes.draw do
    authenticated :user do
        root :to => 'home#index'
    end
    devise_scope :user do
        root :to => "devise/registrations#new"
        match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    end
    devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
    match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
    resources :users do
        get 'invite', :on => :member
    end
end
```

Issue was:
:confirmations => "confirmations"

**Comment by DanielKehoe** [comment]
Could you please clarify? You had neglected to add add `:confirmations => "confirmations"` as shown in the tutorial?

**Comment by davidmolina** [comment]
Yes, that's correct. The "request invite" link/button was not working and was inactive (i.e. nothing happened after clicking on "request invite"). As a first timer building any rails application I copied the original code to a separate .pages document before inserting your tutorial code. I worked backwards in trying to isolate where I went wrong. Oddly, it was that snippet of code that did the trick. Now in the app, new users can sign up and an automatic response is provided thanking them and inviting them to share the app on twitter and fb. 

I'm certain that neglecting  :confirmations => "confirmations" has intended consequences.

**Comment by DanielKehoe** [comment]
Thanks for the clarification. I'm sure it will help others.

I'm glad you were able to resolve the issue. You said this is the first time you are building a Rails application: Welcome to the Rails community!

**Comment by davidmolina** [comment]
Thanks Daniel! I'm stoked to be part of the Rails community. Onto building.
