### ISSUE TITLE
Application template only asks first question.

### ISSUE THREAD

**Issue by djbender** [RailsApps/rails-prelaunch-signup#30]
After asking which branch i wish to use, for prelaunch, none of the other questions are asked. However the app does finish installing. 

I chose the 'prelaunch' branch name.

**Comment by djbender** [comment]
After reviewing the [script](https://github.com/RailsApps/rails3-application-templates/blob/master/rails-prelaunch-signup-template.rb) it looks like a bunch of these preferences are pre-decided. Maybe the README needs to be updated to reflect this?

**Comment by DanielKehoe** [comment]
Thanks for bringing this to my attention. The documentation was pointing to an outdated application template file. I've made the update.

**Comment by MarkDBlackwell** [comment]
If the first question (regarding naming the prelaunch branch) is answered 'master' (as in issue #45) then currently the generator asks a second question, and creates two branches.
