### ISSUE TITLE
Devise views not working in production

### ISSUE THREAD

**Issue by surajreddy** [RailsApps/rails-prelaunch-signup#33]
The app's custom devise views don't seem to be working in production for me.

In development, everything works fine. I see the devise views I'm expecting (from the views/devise folder).

However, as soon as I switch to production, the app starts using the default device gem views.

Any ideas as to what might be going on? I'm assuming this is something really simple that I'm failing to notice.

Thanks!

**Comment by juanfiguera** [comment]
I'm having the same issue :(

**Comment by surajreddy** [comment]
Make sure the project is set up correctly. I missed some errors during the initial set up when using the template. I fixed these and started a new project, and that fixed my problems.

But I still have no idea why it wouldn't work.
