### ISSUE TITLE
Reset password allows login without confirmation

### ISSUE THREAD

**Issue by skierkowski** [RailsApps/rails-prelaunch-signup#35]
If a user requests an invite and users password reminders, they are able to reset the password without the admin first approving them (thus circumventing the approval process). I believe it is because devise automatically sets the user to confirmed when they reset the password.

I used this code on my site and found that about 10% of users did this. I'd like to address this bug so I'd love to hear what you suggest.

**Comment by DanielKehoe** [comment]
Add this to your user.rb file:

```
  def send_reset_password_instructions
    if self.confirmed?
      super
    else
      errors.add :base, "You must receive an invitation before you set your password."
    end
  end
```

Let me know if it resolves the issue. I'll add it to the next version of the example application.

**Comment by DanielKehoe** [comment]
This issue is resolved in the most recent release.
