### ISSUE TITLE
Use gem capybara-webkit instead of Selenium?

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails-prelaunch-signup#39]
Why aren't we using the faster and more normal [capybara-webkit](https://github.com/jnicklas/capybara#capybara-webkit) instead of Selenium?

I presume (with either) we would be testing Javascript code.

Many Cucumber features are failing (for me) without a Firefox binary installed on my Linux box:

```
Could not find Firefox binary (os=linux). Make sure Firefox is installed or set the path manually with Selenium::WebDriver::Firefox::Binary.path= (Selenium::WebDriver::Error::WebDriverError)
      ./features/step_definitions/user_steps.rb:47:in `/^I am not logged in$/'
```

**Comment by DanielKehoe** [comment]
Hmm, @tmock12 could you answer this question?

**Comment by tmock12** [comment]
Javascript testing tends to run into some issues when using headless browsers like capybara-webkit. So far we aren't doing anything extreme so it's fine to use and faster. I just opened a pull request with the change. Thanks Mark for the suggestion.

**Comment by DanielKehoe** [comment]
Thanks @tmock12 for resolving this.
