### ISSUE TITLE
Cannot handle error in sign up

### ISSUE THREAD

**Issue by netwire88** [RailsApps/rails-prelaunch-signup#4]
When user signs up via "Request Invitation" , if there's an error such as duplicate email, RegistrationController.create doesn't return an xhr.error

(render(:partial => 'thankyou', :layout => false) && return) if request.xhr?

And thus this code in application.js doesn't handle error correctly.

$.ajax({
type: "POST",
url: "/users",
data: dataString,
success: function(data) {
$('#request-invite').html(data);
loadSocial();
},
});

and this isn't called:

if ($('.alert-error').length > 0) {
$("#request-invite").modal('toggle');
}

**Comment by DanielKehoe** [comment]
I haven't been able to reproduce this error. I tried entering duplicate email or invalid email and saw the error displayed in the modal dialog as expected. Perhaps this error was corrected in an newer release of the app? I'm going to close the issue. If you can, please test the app using the most recent release and reopen the issue with details I can use to reproduce the error. Thank you!

**Comment by nesmith** [comment]
I had the same issue - I'm not sure exactly what caused it, but my solution was to re-toggle the modal from the view. Right below the form, I added:
-if !@user.errors.nil?
  :javascript
    $("#request-invite").modal('toggle');
Then, when I submitted a form with wrong info, the modal would pop right back up, with the error. I used the same if statement to change the header of the modal form.
