### ISSUE TITLE
Question about branches

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails-prelaunch-signup#45]
Per README section [Git Branches](https://github.com/RailsApps/rails-prelaunch-signup/blob/a9ba8f00ba6840e9cbaf1bde36633fe71b133502/README.textile#git-branches), Rails Composer can [create](https://github.com/RailsApps/rails_apps_composer/blob/6be497cf10dba5fdaf3926fbe55375cfd73e31e0/recipes/railsapps.rb#L135) two branches (if the prelaunch one is 'master') when it generates this Rails Example App:
1. Git branch for the prelaunch app
2. Git branch for the main app

Do they have different contents? Which one is the current repository branch called master? And where is the other one on GitHub?

**Comment by DanielKehoe** [comment]
The app in the GitHub repo is the app created by Rails Composer in the “master” branch. If you tell Rails Composer to create a second branch, the app will be the same. It just names a new branch with the same app for the developer's convenience. The point is to make clear that the developer can have two branches, one for deploying to production and one for work in progress.

**Comment by MarkDBlackwell** [comment]
> If you tell Rails Composer to create a second branch, the app will be the same.

Hm...that would be nice!—but is it really true? :) (BTW, it would be extremely efficient to accomplish it merely by asking Git to check out a new branch from the master branch near the end of things—yet, the Rails Composer doesn't do it quite that way. Instead (as I observe) it does some further regeneration after creating the second branch.)

Admittedly, I'm working from an older rails_apps_composer version. However, when I answered the menu questions in the way that generates two branches, they weren't identical.

This [gist](https://gist.github.com/MarkDBlackwell/5896768) contains the results from:

```
$ rails_apps_composer template generated/composer-core.template.rb
$ rails new generated/rails-prelaunch-signup -m generated/composer-core.template.rb -T
Git branch for the prelaunch app?
          2)  master
Git branch for the main app?
          2)  wip (work-in-progress)
$ cd generated/rails-prelaunch-signup
$ git checkout master
Already on 'master'
$ git branch
* master
  wip
$ git diff wip > ~/out/rails-prelaunch-signup_branch-diff
```

My version:

```
$ pwd
/home/mark/RailsApps/rails_apps_composer
$ git status
# On branch master
nothing to commit (working directory clean)
$ git log -n 1
commit a70f5be3fd58c024042be26736b16e52222771f2
Merge: 60b7c04 3f925ce
Author: Daniel Kehoe <daniel@danielkehoe.com>
Date:   Mon Jun 3 11:27:23 2013 -0700
    Merge pull request #215 from tmock12/capybara-webkit
    Only require capybara-webkit in test environment for rails prelaunch
$ gem list rails_apps_composer
rails_apps_composer (2.2.41)
```

**Comment by MarkDBlackwell** [comment]
Using the current version of rails_apps_composer (2.4.1) I regenerated the example app.

Unfortunately still, branches `master` and `wip` are just as dissimilar as I reported above.

**Comment by MarkDBlackwell** [comment]
If all branches are desired to be identical (e.g., main and prelaunch), then rails_apps_composer's prelaunch.rb recipe file section [Create a git branch](https://github.com/RailsApps/rails_apps_composer/blob/c99c817e0cdfb5d0fd81807bb39cc9fc816c6767/recipes/prelaunch.rb#L27) (it looks to me) should move after the final git commit invoked in section "[### GIT ###](https://github.com/RailsApps/rails_apps_composer/blob/c99c817e0cdfb5d0fd81807bb39cc9fc816c6767/recipes/prelaunch.rb#L105)" at file's end.

However on reflection, it seems (to me) instead these branches should not be identical since branch "wip" contains a rich complement of user login features more typical of an active (not prelaunch) site.

If so, this is the only Rails Example App I am aware of naturally having multiple Git branches—so it is unique in that way. Yet seemingly we could add the main branch to GitHub as well (of course to the same repository), perhaps call it "wip", and give this main branch the same public exposure as the prelaunch branch currently enjoys.

Also this would fulfill the assurance made in README sections [Getting the Application](https://github.com/RailsApps/rails-prelaunch-signup#getting-the-application) and [Clone](https://github.com/RailsApps/rails-prelaunch-signup#clone) that "for getting [all] the code[, one] can clone the GitHub repo." Presumably this would increase the usefulness of its cloning.
