### ISSUE TITLE
Rails 4 `attr_accessible` 

### ISSUE THREAD

**Issue by korabh** [RailsApps/rails-prelaunch-signup#53]
class User < ActiveRecord::Base
  rolify
  attr_accessible :role_ids, :as => :admin
  attr_accessible :provider, :uid, :name, :email

validates_presence_of :name
  def self.create_with_omniauth(auth)
    create! do |user|

**Comment by DanielKehoe** [comment]
You're using Rails 4. This application was written for Rails 3.2 See the README.

**Comment by korabh** [comment]
I know but I'm trying to figure out how to make it work on Rails 4?

**Comment by DanielKehoe** [comment]
Rails 3.2 to Rails 4.0
Ebook: Andy Lindeman Upgrading to Rails 4
Ebook: Philip De Smedt Upgrade to Rails 4
Blog post: Maciej Mensfeld Upgrading to Rails 4.0 from Rails 3.2
Blog post: Mario Chavez Upgrading a Rails application to 4.0
Script: Michael de Silva upgrade_rails_3.2.12_to_4.0.0.beta1
Video: Code School Rails 4: Zombie Outlaws
Article: RailsGuides Upgrading from Rails 3.2 to Rails 4.0 (work-in-progress document)

**Comment by korabh** [comment]
Thank you  :+1:
