### ISSUE TITLE
Using gemset and unable to install Rails 4.1.0

### ISSUE THREAD

**Issue by evanniedojadlo** [RailsApps/rails-prelaunch-signup#57]
I created the suggested rvm gemset within the tutorial and then attempted to install Rails version 4.1.0 (as indicated within the composer tool) and returned the following error in my terminal:

gem install rails -v 4.1.0
ERROR:  While executing gem ... (Gem::Exception)
    Invalid spec cache file in /Users/RAI/.gem/specs/rubygems.org%443/specs.4.8

Note that I am still fairly new with Rails environments and ran a google search which didn't return any useful information. Also note that the rvm gemset that I am using is configured to ruby 2.0.0p481 as indicated in the tutorial.

Thanks and sorry if I missed anything,

**Comment by DanielKehoe** [comment]
The rails-prelaunch-signup app was written for Rails 3.2 and hasn't been updated (no plans to update it either). Try the [Mailing List with Active Job](https://github.com/RailsApps/rails-mailinglist-activejob) starter app instead.

**Comment by evanniedojadlo** [comment]
@DanielKehoe Understood, thanks. I will look into the Mailing List with Active Job project now.
