### ISSUE TITLE
Error code -32601. Can't make it work

### ISSUE THREAD

**Issue by rvgarimrj** [RailsApps/rails-prelaunch-signup#59]
Please, help me I can't make it work. I'm getting the following error from debugger:

(rdb:1) result
{"status"=>"error", "code"=>-32601, "name"=>"ServerError_MethodUnknown", "error"=>"Unknown method \"/2\""}

Using rails 4.1 and ruby 2.1.1

The gist: https://gist.github.com/rvgarimrj/629fd8c70b0a218321b0

**Comment by DanielKehoe** [comment]
The app was written for Rails 3.2. You're running it under Rails 4.1. I'm no longer supporting this application. Please use try using this app instead: https://github.com/RailsApps/rails-mailinglist-activejob
