### ISSUE TITLE
database.yml not found

### ISSUE THREAD

**Issue by Chandra736** [RailsApps/rails-prelaunch-signup#6]
git clone git://github.com/RailsApps/rails-prelaunch-signup.git, I cloned the project from the given link and ran bundle install.

I am getting the following errors: 

C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application/configuration.rb:115:in `read': No such file or directory - D:/work/rails-prelaunch-signup/config/database.yml (Er
rno::ENOENT)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application/configuration.rb:115:in`database_configuration'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/railtie.rb:78:in `block (2 levels) in <class:Railtie>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/lazy_load_hooks.rb:36:in`instance_eval'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/lazy_load_hooks.rb:26:in`block in on_load'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/lazy_load_hooks.rb:25:in `each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/lazy_load_hooks.rb:25:in`on_load'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/railtie.rb:74:in `block in <class:Railtie>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in`instance_exec'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `run'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:55:in`block in run_initializers'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in`run_initializers'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application.rb:136:in `initialize!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/railtie/configurable.rb:30:in`method_missing'
        from D:/work/rails-prelaunch-signup/config/environment.rb:5:in `<top (required)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in`require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `block in require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in`load_dependency'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
        from D:/work/rails-prelaunch-signup/config.ru:4:in`block in <main>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:51:in`initialize'
        from D:/work/rails-prelaunch-signup/config.ru:1:in `new'
        from D:/work/rails-prelaunch-signup/config.ru:1:in`<main>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:40:in `eval'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:40:in`parse_file'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:200:in `app'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/commands/server.rb:46:in`app'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:301:in `wrapped_app'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:252:in`start'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/commands/server.rb:70:in `start'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/commands.rb:55:in`block in <top (required)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/commands.rb:50:in `tap'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/commands.rb:50:in`<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in`<main>'

**Comment by Chandra736** [comment]
I am running this app in windows

**Comment by DanielKehoe** [comment]
I've updated the repo to provide the database.yml file with commit 392d6c45d8b6cf8800e08ba092046c6c954f513a. Thanks for bringing this to my attention. Clone the repo again and let me know if you have everything you need.
