### ISSUE TITLE
The confirmati​on email do not carry current Password/ User unable to set his password

### ISSUE THREAD

**Issue by Chandra736** [RailsApps/rails-prelaunch-signup#7]
The confirmation email for a visitor donot carry the current password, because of this reason user will not be able to change his password. 
Using confirmation link directly it gets logged in and edit account link is given to the use but he can't change his password. Is there any step in between confirmation link and edit account where user sets his password.

**Comment by DanielKehoe** [comment]
I've fixed this bug with commit 0e23639e4591aa4bd7274317919eef96e6ec81b. Not sure why but we've got a default password when the account is created. Corrected by removing the password before saving. If you have any users in your database, you'll need to bulk update the database to set the encrypted_password field to nil for all users except the administrator.

**Comment by DanielKehoe** [comment]
Actually the correct fix is in commit 4d8f44c3558883c805359c5ae18b28e72b759e77. Our application.js was creating a password with a value "undefined". The code was an artifact of an earlier implementation. Corrected now. If you have any users in your database, you'll need to bulk update the database to set the encrypted_password field to nil for all users except the administrator.
